import { Escrow } from '@/types/escrow.types';
import { WalletInfo } from '@/types/wallet.types';
import { Transaction } from '@/types/transaction.types';

// ─── Mock Wallet ─────────────────────────────────────────────────────────────
export const MOCK_WALLET: WalletInfo = {
  address: '0xfK07tgetB84...8336',
  balance: 48.24,
  status: 'connected',
  network: 'devnet',
  lastUpdated: new Date().toISOString(),
};

// ─── Mock Escrows ─────────────────────────────────────────────────────────────
export const MOCK_ESCROWS: Escrow[] = [
  {
    id: 'esc_001',
    contractId: 'KNT-2024-001',
    title: 'Solana NFT Marketplace UI Kit',
    description:
      'Build a complete NFT marketplace frontend with wallet integration, listing pages, and auction UI.',
    status: 'active',
    totalAmount: 145.5,
    lockedAmount: 145.5,
    client: {
      address: '0x98A...fE21',
      displayName: 'DigitalArtisan.sol',
      rating: 4.9,
    },
    freelancer: {
      address: '0x4D2...B836',
      displayName: 'SolDev_Alpha',
      rating: 4.8,
    },
    pdaAddress: '8aDq7zBfWvPz45Lkq8mN2jT9s1XyR3v6B',
    programId: 'kinetex_v2_pda_v1',
    milestones: [
      {
        id: 'ms_001_1',
        title: 'UI Component Library',
        description: 'Design and implement reusable NFT components',
        amount: 48.5,
        dueDate: '2024-11-15',
        status: 'approved',
        submittedAt: '2024-11-12',
        approvedAt: '2024-11-13',
      },
      {
        id: 'ms_001_2',
        title: 'Marketplace Listings Page',
        description: 'Complete listings with filters, sorting, and search',
        amount: 55.0,
        dueDate: '2024-12-01',
        status: 'submitted',
        submittedAt: '2024-11-28',
      },
      {
        id: 'ms_001_3',
        title: 'Auction & Bidding UI',
        description: 'Real-time auction interface with countdown timers',
        amount: 42.0,
        dueDate: '2024-12-20',
        status: 'pending',
      },
    ],
    auditLog: [
      {
        id: 'log_001_1',
        event: 'Program Account Initialized',
        timestamp: '2023-10-12T14:22:10Z',
        txHash: '5z7k...9m2L',
      },
      {
        id: 'log_001_2',
        event: 'Vault Funding: 145.5 SOL',
        timestamp: '2023-10-12T14:25:45Z',
        txHash: '8mPq...3Rv7',
      },
      {
        id: 'log_001_3',
        event: 'Awaiting Work Submission...',
        timestamp: '2023-10-12T14:25:50Z',
        details: 'Timer Running',
      },
    ],
    createdAt: '2023-10-12T14:22:10Z',
    updatedAt: '2024-11-28T10:15:00Z',
    timeoutDate: '2024-12-31T00:00:00Z',
    network: 'devnet',
  },
  {
    id: 'esc_002',
    contractId: 'KNT-2024-002',
    title: 'Smart Contract Audit Report',
    description:
      'Comprehensive security audit of DeFi protocol smart contracts.',
    status: 'pending',
    totalAmount: 15.0,
    lockedAmount: 15.0,
    client: {
      address: '0x82...1f2',
      displayName: 'DeFiProtocol.sol',
      rating: 4.7,
    },
    freelancer: {
      address: '0xc3...9a4',
      displayName: 'AuditExpert.sol',
      rating: 5.0,
    },
    pdaAddress: '9bEr8yGhXwQa56Mjp9nN3kU0t2ZyS4v7C',
    programId: 'kinetex_v2_pda_v1',
    milestones: [
      {
        id: 'ms_002_1',
        title: 'Initial Code Review',
        description: 'Static analysis and initial vulnerability scan',
        amount: 5.0,
        dueDate: '2024-11-20',
        status: 'in_progress',
      },
      {
        id: 'ms_002_2',
        title: 'Full Audit Report',
        description: 'Complete findings report with recommendations',
        amount: 10.0,
        dueDate: '2024-12-05',
        status: 'pending',
      },
    ],
    auditLog: [
      {
        id: 'log_002_1',
        event: 'Escrow Funded: 15 SOL',
        timestamp: '2024-11-18T09:30:00Z',
        txHash: '3xPm...5Ks9',
      },
    ],
    createdAt: '2024-11-18T09:30:00Z',
    updatedAt: '2024-11-18T09:30:00Z',
    timeoutDate: '2024-12-15T00:00:00Z',
    network: 'devnet',
  },
  {
    id: 'esc_003',
    contractId: 'KNT-2024-003',
    title: 'Frontend React Development',
    description:
      'Build complete React frontend for a Solana-based lending protocol.',
    status: 'active',
    totalAmount: 38.75,
    lockedAmount: 20.0,
    client: {
      address: '0xa4...7c3',
      displayName: 'LendFi_DAO',
      rating: 4.6,
    },
    freelancer: {
      address: '0xd5...2b8',
      displayName: 'ReactWizard.sol',
      rating: 4.9,
    },
    pdaAddress: '7cFs6xHiYvRb34Lnq8mK1jP0s3WzT5u8D',
    programId: 'kinetex_v2_pda_v1',
    milestones: [
      {
        id: 'ms_003_1',
        title: 'Design System & Components',
        description: 'Token swapping and lending UI components',
        amount: 12.5,
        dueDate: '2024-11-25',
        status: 'released',
        submittedAt: '2024-11-22',
        approvedAt: '2024-11-23',
      },
      {
        id: 'ms_003_2',
        title: 'Dashboard Integration',
        description: 'Position management and analytics dashboard',
        amount: 14.25,
        dueDate: '2024-12-10',
        status: 'submitted',
        submittedAt: '2024-12-08',
      },
      {
        id: 'ms_003_3',
        title: 'Mobile Responsive Polish',
        description: 'Full responsive design and optimization',
        amount: 12.0,
        dueDate: '2024-12-25',
        status: 'pending',
      },
    ],
    auditLog: [
      {
        id: 'log_003_1',
        event: 'Contract Initialized',
        timestamp: '2024-11-10T11:00:00Z',
        txHash: '9yKn...2Wq4',
      },
      {
        id: 'log_003_2',
        event: 'Milestone 1 Funds Released: 12.5 SOL',
        timestamp: '2024-11-23T16:45:00Z',
        txHash: '4mJr...7Xt6',
      },
    ],
    createdAt: '2024-11-10T11:00:00Z',
    updatedAt: '2024-12-08T09:20:00Z',
    timeoutDate: '2025-01-15T00:00:00Z',
    network: 'devnet',
  },
  {
    id: 'esc_004',
    contractId: 'KNT-2024-004',
    title: 'Mobile App Prototype',
    description: 'Cross-platform mobile app for Solana portfolio tracking.',
    status: 'completed',
    totalAmount: 8.4,
    lockedAmount: 0,
    client: {
      address: '0xb2...9e1',
      displayName: 'CryptoMobile.sol',
      rating: 4.8,
    },
    freelancer: {
      address: '0xe6...3c7',
      displayName: 'MobileBuilder.sol',
      rating: 4.7,
    },
    pdaAddress: '6aBt5wGjZuSc23Kop7nM0iQ9r4VyU6t9E',
    programId: 'kinetex_v2_pda_v1',
    milestones: [
      {
        id: 'ms_004_1',
        title: 'Full App Delivery',
        description: 'Complete mobile app with all features',
        amount: 8.4,
        dueDate: '2024-10-30',
        status: 'released',
        submittedAt: '2024-10-28',
        approvedAt: '2024-10-29',
      },
    ],
    auditLog: [
      {
        id: 'log_004_1',
        event: 'Escrow Initialized',
        timestamp: '2024-10-15T08:00:00Z',
        txHash: '2nLp...8Mv5',
      },
      {
        id: 'log_004_2',
        event: 'Funds Released: 8.4 SOL',
        timestamp: '2024-10-29T14:30:00Z',
        txHash: '7qWs...1Nt3',
      },
    ],
    createdAt: '2024-10-15T08:00:00Z',
    updatedAt: '2024-10-29T14:30:00Z',
    timeoutDate: '2024-11-30T00:00:00Z',
    network: 'devnet',
  },
  {
    id: 'esc_005',
    contractId: 'KNT-2024-005',
    title: 'Tokenomics Design & Whitepaper',
    description: 'Economic model design, token distribution, and whitepaper.',
    status: 'disputed',
    totalAmount: 22.0,
    lockedAmount: 22.0,
    client: {
      address: '0xf7...4a2',
      displayName: 'LaunchPad_DAO',
      rating: 3.9,
    },
    freelancer: {
      address: '0xa8...6d5',
      displayName: 'TokenEcon.sol',
      rating: 4.3,
    },
    pdaAddress: '5dCu4vFkAsTb12Jnq6mL9hR0p5XzW7r0F',
    programId: 'kinetex_v2_pda_v1',
    milestones: [
      {
        id: 'ms_005_1',
        title: 'Tokenomics Model',
        description: 'Economic framework and distribution model',
        amount: 12.0,
        dueDate: '2024-11-10',
        status: 'submitted',
        submittedAt: '2024-11-09',
      },
      {
        id: 'ms_005_2',
        title: 'Whitepaper Draft',
        description: 'Full whitepaper with technical specifications',
        amount: 10.0,
        dueDate: '2024-11-30',
        status: 'pending',
      },
    ],
    auditLog: [
      {
        id: 'log_005_1',
        event: 'Escrow Initialized',
        timestamp: '2024-10-20T12:00:00Z',
        txHash: '8xQr...6Ps2',
      },
      {
        id: 'log_005_2',
        event: 'Dispute Raised by Client',
        timestamp: '2024-11-12T16:20:00Z',
        txHash: '1mTv...9Uw7',
      },
    ],
    createdAt: '2024-10-20T12:00:00Z',
    updatedAt: '2024-11-12T16:20:00Z',
    timeoutDate: '2024-12-20T00:00:00Z',
    network: 'devnet',
  },
];

// ─── Mock Transactions ────────────────────────────────────────────────────────
export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx_001',
    type: 'escrow_funded',
    description: 'Escrow Funded: Smart Contract Audit',
    amount: 15.0,
    timestamp: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    txHash: '0x82...1f2',
    status: 'finalized',
    escrowId: 'esc_002',
  },
  {
    id: 'tx_002',
    type: 'work_submitted',
    description: 'Work Submitted: Frontend React Dev',
    timestamp: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    txHash: '0xa4...7c3',
    status: 'processing',
    escrowId: 'esc_003',
  },
  {
    id: 'tx_003',
    type: 'funds_released',
    description: 'Funds Released: Mobile App Prototype',
    amount: 8.4,
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    txHash: '0xb2...9e1',
    status: 'finalized',
    escrowId: 'esc_004',
  },
  {
    id: 'tx_004',
    type: 'milestone_approved',
    description: 'Milestone Approved: UI Component Library',
    amount: 48.5,
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    txHash: '0xc9...5d4',
    status: 'finalized',
    escrowId: 'esc_001',
  },
  {
    id: 'tx_005',
    type: 'dispute_raised',
    description: 'Dispute Raised: Tokenomics Design',
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    txHash: '0xd1...8e3',
    status: 'finalized',
    escrowId: 'esc_005',
  },
];

// ─── Stats ────────────────────────────────────────────────────────────────────
export const MOCK_STATS = {
  activeEscrows: 1248,
  totalVolumeSol: 42890.5,
  completedContracts: 3102,
  pendingApprovals: 14,
  networkTps: 3482,
  successRate: 94.7,
};

// ─── Chart Data ───────────────────────────────────────────────────────────────
export const MOCK_CHART_DATA = [
  { month: 'Jun', volume: 12.4, contracts: 8 },
  { month: 'Jul', volume: 18.7, contracts: 12 },
  { month: 'Aug', volume: 15.2, contracts: 10 },
  { month: 'Sep', volume: 24.8, contracts: 16 },
  { month: 'Oct', volume: 31.5, contracts: 21 },
  { month: 'Nov', volume: 28.9, contracts: 19 },
  { month: 'Dec', volume: 48.24, contracts: 28 },
];
